data<- read.csv("cows.csv", header = TRUE, sep = ",")
plot(data)
fit <- lm(price ~ ., data=data)
summary(fit)
fit2 <- update(fit,.~.-breed)
summary(fit2)
fit3 <- update(fit2,.~.-yearling_height)
summary(fit3)
fit4 <- update(fit3,.~.-sale_weight)
summary(fit4)
fit5 <- update(fit4,.~.-percent_fat)
summary(fit5)
plot(fit4)
plot(resid(fit4))
qqnorm(resid(fit4))

png('cow%03d.png',width=6,height=6,units='in',res=300)
layout(matrix(1:4, ncol=2))
plot(fit4)
layout(1)
dev.off()